### ISSUE TITLE
Load unpacked error

### ISSUE THREAD

**Issue by eduOS** [th0rgall/voc-enhancer#15]
I built the extension from the 0.4.7 release and loaded the ./dist/chrome to the chrome extension but the following error occurs: 

> Uncaught ReferenceError: VocAPI is not defined

![image](https://user-images.githubusercontent.com/8926535/128945474-382582ce-315d-46a3-aabf-7a534afc135f.png)

I have installed the voc-api under the repo directory and no errors showed up after I entered make to build the extension dist. 

Any suggestions?

**Comment by th0rgall** [comment]
Hey @eduOS , it seems the `make` is a remnant of an old version. I believe it was substituted with a webpack setup. As you can see, this package was not left in an ideal state, without development instructions, and has been unmaintained for two years. I don't have time to fix that now unfortunately.

But I could get the project to compile again here with the following command:

`npx webpack --mode=development`

This should take care of the voc-api import here (https://github.com/th0rgall/voc-enhancer/blob/6f22c0d6f5e149f85515b7ff6ba7ce9fec6b56aa/src/background.js#L3-L4). Thus: try to use webpack with the config https://github.com/th0rgall/voc-enhancer/blob/master/webpack.config.js instead of `make`.
